name = "jadpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37e8cf7a1b2ee7fc7370419521dd5b1f6ec652de419dfead5ce05f44f58206df"

[versions]
fabric = "0.10.6+build.214"
minecraft = "1.16.3"
