name = "jadpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2acd022fddecc15f542264f0a24d5ba7599cfad8ea6cf0a0bc3108709c22d12"

[versions]
fabric = "0.10.6+build.214"
minecraft = "1.16.3"
