name = "jadpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "929f9bac3b14b0e427c16b2be7b1dca32fedf7a1ef65e31da3e3545bbd7b6eae"

[versions]
fabric = "0.10.6+build.214"
minecraft = "1.16.3"
