name = "jadpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ccc3ff92d023ce6eb7b10a8e37f4405c3f4daaeccfdbbc5ed25ff0254a3fd95"

[versions]
fabric = "0.10.6+build.214"
minecraft = "1.16.3"
