name = "AdventureZ"
filename = "adventurez-1.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3084/222/adventurez-1.1.3.jar"
hash-format = "murmur2"
hash = "3870624239"

[update]
[update.curseforge]
file-id = 3084222
project-id = 390991
release-channel = "beta"
