name = "BackSlot"
filename = "backslot-1.1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3085/277/backslot-1.1.6.jar"
hash-format = "murmur2"
hash = "645350134"

[update]
[update.curseforge]
file-id = 3085277
project-id = 402739
release-channel = "beta"
