name = "BetterNether"
filename = "better-nether-4.1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3099/928/better-nether-4.1.8.jar"
hash-format = "murmur2"
hash = "3029592401"

[update]
[update.curseforge]
file-id = 3099928
project-id = 311377
release-channel = "beta"
