name = "Cardinal Components"
filename = "Cardinal-Components-API-2.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/963/Cardinal-Components-API-2.7.3.jar"
hash-format = "murmur2"
hash = "2086435016"

[update]
[update.curseforge]
file-id = 3100963
project-id = 318449
release-channel = "beta"
