name = "Chat Heads"
filename = "chat_heads-0.2.0+1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3096/37/chat_heads-0.2.0+1.16.2.jar"
hash-format = "murmur2"
hash = "479007163"

[update]
[update.curseforge]
file-id = 3096037
project-id = 407206
release-channel = "beta"
