name = "Door(s) Coupling [FABRIC]"
filename = "Couplings-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3094/851/Couplings-1.3.4.jar"
hash-format = "murmur2"
hash = "3835870907"

[update]
[update.curseforge]
file-id = 3094851
project-id = 395659
release-channel = "beta"
