name = "Damage Tilt"
filename = "DamageTilt-1.16-forge-0.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3077/428/DamageTilt-1.16-forge-0.1.1.jar"
hash-format = "murmur2"
hash = "1055683286"

[update]
[update.curseforge]
file-id = 3077428
project-id = 411705
release-channel = "beta"
