name = "Dynamic Sound Filters"
filename = "DynamicSoundFilters-1.1.3+1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3029/490/DynamicSoundFilters-1.1.3+1.16.2.jar"
hash-format = "murmur2"
hash = "1514147568"

[update]
[update.curseforge]
file-id = 3029490
project-id = 392101
release-channel = "beta"
