name = "Fabric API"
filename = "fabric-api-0.25.0+build.415-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3097/415/fabric-api-0.25.0+build.415-1.16.jar"
hash-format = "murmur2"
hash = "1924095965"

[update]
[update.curseforge]
file-id = 3097415
project-id = 306612
release-channel = "beta"
