name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.4.0+build.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3048/355/fabric-language-kotlin-1.4.0+build.1.jar"
hash-format = "murmur2"
hash = "1377344559"

[update]
[update.curseforge]
file-id = 3048355
project-id = 308769
release-channel = "beta"
