name = "Fabric Furnaces"
filename = "fabric-furnaces-1.3.2-1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3049/271/fabric-furnaces-1.3.2-1.16.2.jar"
hash-format = "murmur2"
hash = "3108168161"

[update]
[update.curseforge]
file-id = 3049271
project-id = 315534
release-channel = "beta"
