name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3101/660/fallingleaves-1.0.jar"
hash-format = "murmur2"
hash = "1637142525"

[update]
[update.curseforge]
file-id = 3101660
project-id = 417510
release-channel = "beta"
