name = "Illuminations 🔥"
filename = "illuminations-1.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3096/447/illuminations-1.2.3.jar"
hash-format = "murmur2"
hash = "987054319"

[update]
[update.curseforge]
file-id = 3096447
project-id = 292908
release-channel = "beta"
