name = "Inmis"
filename = "inmis-1.3.1-1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/557/inmis-1.3.1-1.16.2.jar"
hash-format = "murmur2"
hash = "3607215568"

[update]
[update.curseforge]
file-id = 3100557
project-id = 369254
release-channel = "beta"
