name = "LambDynamicLights"
filename = "lambdynamiclights-fabric-1.3.1+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3068/417/lambdynamiclights-fabric-1.3.1+1.16.3.jar"
hash-format = "murmur2"
hash = "2784346789"

[update]
[update.curseforge]
file-id = 3068417
project-id = 393442
release-channel = "beta"
