name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.16.3-0.5.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/230/lithium-fabric-mc1.16.3-0.5.6.jar"
hash-format = "murmur2"
hash = "2077916741"

[update]
[update.curseforge]
file-id = 3063230
project-id = 360438
release-channel = "beta"
