name = "Netherite Plus"
filename = "netherite-plus-mod-1.1.0-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3101/553/netherite-plus-mod-1.1.0-1.16.4.jar"
hash-format = "murmur2"
hash = "3634891700"

[update]
[update.curseforge]
file-id = 3101553
project-id = 394120
release-channel = "beta"
