name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures-1.16.3-1.6.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3094/28/repurposed_structures-1.16.3-1.6.9.jar"
hash-format = "murmur2"
hash = "2322098338"

[update]
[update.curseforge]
file-id = 3094028
project-id = 391366
release-channel = "beta"
