name = "'Slight' Gui Modifications"
filename = "slight-gui-modifications-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3083/832/slight-gui-modifications-1.5.0.jar"
hash-format = "murmur2"
hash = "147386028"

[update]
[update.curseforge]
file-id = 3083832
project-id = 380393
release-channel = "beta"
