name = "Straighten Up"
filename = "straighten-up-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3027/796/straighten-up-1.0.1.jar"
hash-format = "murmur2"
hash = "2809948432"

[update]
[update.curseforge]
file-id = 3027796
project-id = 341351
release-channel = "beta"
