name = "Xaero's Minimap"
filename = "Xaeros_Minimap_20.27.2_Fabric_1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3100/948/Xaeros_Minimap_20.27.2_Fabric_1.16.4.jar"
hash-format = "murmur2"
hash = "493094676"

[update]
[update.curseforge]
file-id = 3100948
project-id = 263420
release-channel = "beta"
